[[introducao]]
= Introdução

O objectivo deste livro é proporcionar uma instrução clara e uma
reflexão sobre meditação budista, tal como é ensinada por Ajahn Sumedho,
um bhikkhu (monge) da tradição Theravada. Os capítulos seguintes foram
editados a partir de palestras mais longas proferidas por Ajahn Sumedho
a meditadores, como uma abordagem prática à sabedoria do Budismo. Esta
sabedoria é também conhecida como Dhamma.

Somos convidados a usar este livro como um manual, passo-a-passo. O
primeiro capítulo tenta apresentar uma visão geral da prática do Budismo
e as secções subsequentes podem ser entendidas uma a uma e seguidas de
um período de meditação. O terceiro capítulo é uma reflexão sobre a
compreensão que se desenvolve através da meditação. O livro termina com
a forma de tomar os Refúgios e os Preceitos o que redimensiona a prática
da meditação dentro do contexto mais abrangente do trabalho a ter com a
mente. Estes podem ser pedidos formalmente aos monásticos budistas
(Saṅgha) ou serem assumidos pessoalmente. Eles constituem os
pressupostos através dos quais os valores espirituais são trazidos ao
mundo.

A primeira edição deste livro, em inglês, (2.000 cópias) foi impressa em
1985 – aquando da abertura do Centro Budista Amarāvatī – tendo esta se
esgotado rapidamente. O livro foi muito apreciado e algumas pessoas
ofereceram-se para patrocinar uma nova impressão; desta forma fizemos
uma revisão mais meticulosa do que a anterior e adicionámos algum design
para melhorar o livro como um todo; à parte disso o texto manteve-se.
Como este livro foi inteiramente produzido através de contribuições
voluntárias e de serviço ao Dhamma, é pedido aos leitores que respeitem
esta oferenda, mantendo-a disponível de forma gratuita.

Possam todos os seres realizar a Verdade.

Venerável Succito +
Centro Budista Amarāvatī +
Maio 1986
